### ISSUE TITLE
Login Url Connection Issue

### ISSUE THREAD

**Issue by AyselHavutcu** [VERO-Digital-Solutions/web-portal-task#2]
Hi , 
I get the following error when I try to authorize the API. I even used the code block you provided.

SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot open database "baubuddy_test" requested by the login. The login failed.1

I was able to get the data yesterday. I searched for the issue. It seems to be a connection error. 
Thank you in advance.

**Comment by Dima-369** [comment]
Yeah, we have connection errors right now. Sorry, it should work in a few hours!

**Comment by AyselHavutcu** [comment]
Fixed. Thanks,
